export const ACTION_MANUAL_ADD_NEW_PLAYER = 'ACTION_MANUAL_ADD_NEW_PLAYER';
export const ACTION_MANUAL_REMOVE_PLAYER = 'ACTION_MANUAL_REMOVE_PLAYER';

export const ACTION_MANUAL_ADD_GAME_ROLE = 'ACTION_MANUAL_ADD_GAME_ROLE';
export const ACTION_MANUAL_EDIT_GAME_ROLE = 'ACTION_MANUAL_EDIT_GAME_ROLE';
export const ACTION_MANUAL_REMOVE_GAME_ROLE = 'ACTION_MANUAL_REMOVE_GAME_ROLE';

export const ACTION_MANUAL_START_EDITING_ROLE = 'ACTION_MANUAL_START_EDITING_ROLE';
export const ACTION_MANUAL_FINISH_EDITING_ROLE = 'ACTION_MANUAL_FINISH_EDITING_ROLE';

export const ACTION_MANUAL_HAS_EDITED_ROLE = 'ACTION_MANUAL_HAS_EDITED_ROLE';