export const ACTION_MANUAL_ADD_NEW_PLAYER = 'ACTION_MANUAL_ADD_NEW_PLAYER';
export const ACTION_MANUAL_REMOVE_PLAYER = 'ACTION_MANUAL_REMOVE_PLAYER';

export const ACTION_MANUAL_ADD_GAME_ROLE = 'ACTION_MANUAL_ADD_GAME_ROLE';
export const ACTION_MANUAL_EDIT_GAME_ROLE = 'ACTION_MANUAL_EDIT_GAME_ROLE';
export const ACTION_MANUAL_REMOVE_GAME_ROLE = 'ACTION_MANUAL_REMOVE_GAME_ROLE';

export const ACTION_START_LOADING = 'ACTION_START_LOADING';
export const ACTION_STOP_LOADING = 'ACTION_STOP_LOADING';